---
abstract: 'a tied hash that requires modules for you'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Hash
name: Module-Hash
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Module::Runtime: 0.002
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Module-Hash
  homepage: https://metacpan.org/release/Module-Hash
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-module-hash
version: 0.001
